# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazynotion < Formula
  desc "A terminal UI for browsing and editing Notion pages."
  homepage "https://github.com/affine1129/lazynotion"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_darwin_amd64.tar.gz"
      sha256 "14013ce31c0b9b3b05a4fd1018ff22a4751915285e6e72ea34a054197b5e947d"

      define_method(:install) do
        bin.install "lazynotion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_darwin_arm64.tar.gz"
      sha256 "5877734421ec47a2d0d2faa2ac6a1a8c27d9f21d3d95f3a29fff81f945288221"

      define_method(:install) do
        bin.install "lazynotion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_linux_amd64.tar.gz"
      sha256 "d212b7ae79fdce610746ad16856354bddd100a7f2d67ec0679f6dd6b07fdf48e"
      define_method(:install) do
        bin.install "lazynotion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_linux_arm64.tar.gz"
      sha256 "5b92b79076df464d286d8d23f08e539cb9977486e30ff466584013a5bde83234"
      define_method(:install) do
        bin.install "lazynotion"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazynotion --version")
  end
end
