# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazynotion < Formula
  desc "A terminal UI for browsing and editing Notion pages."
  homepage "https://github.com/affine1129/lazynotion"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_darwin_amd64.tar.gz"
      sha256 "8cfee4cfc9cfa68825f46793b2076c2805ca3cc28d22015042b5b434bf5a27d4"

      define_method(:install) do
        bin.install "lazynotion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_darwin_arm64.tar.gz"
      sha256 "f4b9863e88c6d376958789e5ce0a0c890282eb807d037f9832ba1a82095b5892"

      define_method(:install) do
        bin.install "lazynotion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_linux_amd64.tar.gz"
      sha256 "6255dff102edfc07a20d292ecd5d1de10fa2c3c1b319629d20ab7c92711ca02b"
      define_method(:install) do
        bin.install "lazynotion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/affine1129/lazynotion/releases/download/v0.1.0/lazynotion_0.1.0_linux_arm64.tar.gz"
      sha256 "4827f467beb33ef5a104a98dded418e4202207a969a6ea82d12445ec4975d01d"
      define_method(:install) do
        bin.install "lazynotion"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazynotion --version")
  end
end
